steps:
  - name: 'node:20'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}" >> .env.production
        echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}" >> .env.production
        echo "NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}" >> .env.production
        echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}" >> .env.production
        echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}" >> .env.production
        echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}" >> .env.production
        
        echo "NEXT_PUBLIC_BACKEND_PUBLIC_API_URL=${NEXT_PUBLIC_BACKEND_PUBLIC_API_URL}" >> .env.production
        echo "NEXT_PUBLIC_BACKEND_PUBLIC_API_URL_FOR_IMG=${NEXT_PUBLIC_BACKEND_PUBLIC_API_URL_FOR_IMG}" >> .env.production

        npm install
        npm run build

images:
  - asia-south1-docker.pkg.dev/glowing-thunder-479313-p3/nextjs-repo/frontend
